export const problems = [
  { id: 1, title: "Two Sum", acceptance: "48.7%", difficulty: "Easy" },
  {
    id: 2,
    title: "Add Two Numbers",
    acceptance: "41.2%",
    difficulty: "Med.",
  },
  {
    id: 3,
    title: "Longest Substring Without Repeating Characters",
    acceptance: "33.4%",
    difficulty: "Med.",
  },
  {
    id: 4,
    title: "Median of Two Sorted Arrays",
    acceptance: "29.8%",
    difficulty: "Hard",
  },
  {
    id: 5,
    title: "Longest Palindromic Substring",
    acceptance: "32.1%",
    difficulty: "Med.",
  },
  {
    id: 6,
    title: "Zigzag Conversion",
    acceptance: "48.1%",
    difficulty: "Med.",
  },
  { id: 7, title: "Reverse Integer", acceptance: "27.4%", difficulty: "Easy" },
  {
    id: 8,
    title: "String to Integer (atoi)",
    acceptance: "16.3%",
    difficulty: "Med.",
  },
  {
    id: 9,
    title: "Palindrome Number",
    acceptance: "55.0%",
    difficulty: "Easy",
  },
  {
    id: 10,
    title: "Regular Expression Matching",
    acceptance: "29.7%",
    difficulty: "Hard",
  },
  {
    id: 11,
    title: "Container With Most Water",
    acceptance: "55.3%",
    difficulty: "Med.",
  },
  {
    id: 12,
    title: "Integer to Roman",
    acceptance: "54.2%",
    difficulty: "Med.",
  },
  {
    id: 13,
    title: "Roman to Integer",
    acceptance: "58.6%",
    difficulty: "Easy",
  },
  {
    id: 14,
    title: "Longest Common Prefix",
    acceptance: "42.0%",
    difficulty: "Easy",
  },
  { id: 15, title: "3Sum", acceptance: "30.1%", difficulty: "Med." },
  {
    id: 16,
    title: "Letter Combinations of a Phone Number",
    acceptance: "55.6%",
    difficulty: "Med.",
  },
  {
    id: 17,
    title: "Valid Parentheses",
    acceptance: "42.9%",
    difficulty: "Easy",
  },
  {
    id: 18,
    title: "Merge Two Sorted Lists",
    acceptance: "61.5%",
    difficulty: "Easy",
  },
  {
    id: 19,
    title: "Generate Parentheses",
    acceptance: "70.5%",
    difficulty: "Med.",
  },
  {
    id: 20,
    title: "Remove Nth Node From End of List",
    acceptance: "39.2%",
    difficulty: "Med.",
  },
  { id: 21, title: "Valid Sudoku", acceptance: "57.8%", difficulty: "Med." },
  { id: 22, title: "Sudoku Solver", acceptance: "53.3%", difficulty: "Hard" },
  { id: 23, title: "Count and Say", acceptance: "48.5%", difficulty: "Med." },
  {
    id: 24,
    title: "Combination Sum",
    acceptance: "71.2%",
    difficulty: "Med.",
  },
  {
    id: 25,
    title: "First Missing Positive",
    acceptance: "39.6%",
    difficulty: "Hard",
  },
  {
    id: 26,
    title: "Trapping Rain Water",
    acceptance: "55.1%",
    difficulty: "Hard",
  },
  { id: 27, title: "Jump Game", acceptance: "51.3%", difficulty: "Med." },
  {
    id: 28,
    title: "Multiply Strings",
    acceptance: "38.7%",
    difficulty: "Med.",
  },
  {
    id: 29,
    title: "Wildcard Matching",
    acceptance: "26.8%",
    difficulty: "Hard",
  },
  {
    id: 30,
    title: "Merge Intervals",
    acceptance: "56.2%",
    difficulty: "Med.",
  },
  {
    id: 31,
    title: "Search in Rotated Sorted Array",
    acceptance: "39.4%",
    difficulty: "Med.",
  },
  {
    id: 32,
    title: "Find Minimum in Rotated Sorted Array",
    acceptance: "45.7%",
    difficulty: "Med.",
  },
  {
    id: 33,
    title: "Find Peak Element",
    acceptance: "49.1%",
    difficulty: "Med.",
  },
  {
    id: 34,
    title: "Majority Element",
    acceptance: "61.1%",
    difficulty: "Easy",
  },
  { id: 35, title: "Missing Number", acceptance: "65.5%", difficulty: "Easy" },
  { id: 36, title: "Power of Two", acceptance: "51.2%", difficulty: "Easy" },
  { id: 37, title: "Climbing Stairs", acceptance: "65.4%", difficulty: "Easy" },
  { id: 38, title: "House Robber", acceptance: "48.5%", difficulty: "Med." },
  {
    id: 39,
    title: "Course Schedule",
    acceptance: "44.8%",
    difficulty: "Med.",
  },
  {
    id: 40,
    title: "Number of Islands",
    acceptance: "55.3%",
    difficulty: "Med.",
  },
  { id: 41, title: "Word Ladder", acceptance: "38.0%", difficulty: "Hard" },
  {
    id: 42,
    title: "Maximum Depth of Binary Tree",
    acceptance: "75.0%",
    difficulty: "Easy",
  },
  {
    id: 43,
    title: "Invert Binary Tree",
    acceptance: "78.9%",
    difficulty: "Easy",
  },
  {
    id: 44,
    title: "Diameter of Binary Tree",
    acceptance: "55.2%",
    difficulty: "Easy",
  },
  { id: 45, title: "Same Tree", acceptance: "56.1%", difficulty: "Easy" },
  {
    id: 46,
    title: "Subtree of Another Tree",
    acceptance: "48.8%",
    difficulty: "Easy",
  },
  {
    id: 47,
    title: "Binary Tree Level Order Traversal",
    acceptance: "63.1%",
    difficulty: "Med.",
  },
  { id: 48, title: "Symmetric Tree", acceptance: "57.3%", difficulty: "Easy" },
  { id: 49, title: "Path Sum", acceptance: "49.9%", difficulty: "Easy" },
  {
    id: 50,
    title: "Lowest Common Ancestor of a BST",
    acceptance: "54.6%",
    difficulty: "Med.",
  },
];
