export const topics = [
  { name: "Array", count: 245 },
  { name: "String", count: 309 },
  { name: "Hash Table", count: 144 },
  { name: "Math", count: 419 },
  { name: "Dynamic Programming", count: 477 },
  { name: "Sorting", count: 363 },
  { name: "Greedy", count: 174 },
  { name: "Depth‑First Search", count: 247 },
  { name: "Breadth‑First Search", count: 473 },
  { name: "Binary Search", count: 170 },
  { name: "Tree", count: 453 },
  { name: "Binary Tree", count: 304 },
  { name: "Matrix", count: 204 },
  { name: "Two Pointers", count: 494 },
  { name: "Stack", count: 148 },
  { name: "Heap (Priority Queue)", count: 225 },
  { name: "Backtracking", count: 461 },
  { name: "Graph", count: 401 },
  { name: "Union Find", count: 359 },
  { name: "Linked List", count: 381 },
  { name: "Sliding Window", count: 295 },
  { name: "Trie", count: 312 },
  { name: "Design", count: 494 },
  { name: "Topological Sort", count: 450 },
  { name: "Recursion", count: 118 },
  { name: "Bit Manipulation", count: 447 },
  { name: "Prefix Sum", count: 366 },
  { name: "Counting", count: 406 },
  { name: "Segment Tree", count: 352 },
  { name: "Binary Indexed Tree", count: 271 },
  { name: "Monotonic Stack", count: 436 },
  { name: "Queue", count: 187 },
  { name: "Memoization", count: 356 },
  { name: "Number Theory", count: 440 },
  { name: "Divide and Conquer", count: 382 },
  { name: "Geometry", count: 423 },
  { name: "Simulation", count: 325 },
  { name: "Enumeration", count: 375 },
  { name: "Game Theory", count: 353 },
  { name: "Minimum Spanning Tree", count: 176 },
  { name: "Line Sweep", count: 489 },
  { name: "Rolling Hash", count: 213 },
  { name: "Ordered Set", count: 336 },
  { name: "Hash Function", count: 499 },
  { name: "Combinatorics", count: 125 },
  { name: "Interactive", count: 126 },
  { name: "Data Stream", count: 346 },
  { name: "Brainteaser", count: 452 },
  { name: "Randomized", count: 223 },
  { name: "Concurrency", count: 106 },
  { name: "Probability and Statistics", count: 163 },
  { name: "Quickselect", count: 108 },
  { name: "Merge Sort", count: 471 },
];
